name: Automerge

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://goharyhesham:${{secrets.GITHUB_TOKEN}}@github.com/goharyhesham/automerge-test2

  # Base branch to merge into
  MY_BRANCH: test

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/goharyhesham/automerge-test2

  # source branch to merge from
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "svc-DigitalInvestor"
        git config user.email "svc-DigitalInvestor@sscinc.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
